/**
 * Redirects from old URLs: .vitepress/config/rewrites.json is the only source.
 * Usage:
 *   node scripts/redirects.mjs check   validate the list (CI)
 *   node scripts/redirects.mjs nginx   write .vitepress/dist/redirects.nginx.conf (after vitepress build)
 * The nginx file holds `location = /old { return 301 /new; }` blocks for the server context:
 * the site's server block includes it, and nginx needs a reload to pick up a changed list.
 * check fails when a target page is missing, a source is itself a page (the redirect would hide it),
 * a target is another redirect, a source repeats, or a URL has characters unsafe for the nginx config.
 */
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DOCS = join(ROOT, 'docs')
const SOURCE = join(ROOT, '.vitepress/config/rewrites.json')
const OUT = join(ROOT, '.vitepress/dist/redirects.nginx.conf')
const OUT_URL = '/redirects.nginx.conf'

/** Plain URL paths only: anything else would need quoting in the nginx config. */
const SAFE_URL = /^\/[A-Za-z0-9._~,\-/]*$/

const mode = process.argv[2]
if (!['check', 'nginx'].includes(mode) || process.argv.length > 3) {
  console.error('Usage: node scripts/redirects.mjs check|nginx')
  process.exit(1)
}

const trimSlash = (url) => url.replace(/\/+$/, '') || '/'

function isPage(url) {
  const path = trimSlash(url).replace(/^\//, '')
  if (path === '') return existsSync(join(DOCS, 'index.md'))
  return existsSync(join(DOCS, `${path}.md`)) || existsSync(join(DOCS, path, 'index.md'))
}

function load() {
  let data
  try {
    data = JSON.parse(readFileSync(SOURCE, 'utf8'))
  } catch (err) {
    console.error(`${SOURCE}: ${err.message}`)
    process.exit(1)
  }
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    console.error(`${SOURCE}: expected an object {"/old": "/new"}`)
    process.exit(1)
  }
  return Object.entries(data)
}

function validate(entries) {
  const errors = []
  const sources = new Map()
  for (const [from, to] of entries) {
    if (typeof to !== 'string') {
      errors.push(`${from}: target is not a string`)
      continue
    }
    for (const url of [from, to]) {
      if (!SAFE_URL.test(url)) errors.push(`${from}: unsafe URL ${JSON.stringify(url)}`)
    }
    const key = trimSlash(from)
    if (sources.has(key)) errors.push(`${from}: duplicates ${sources.get(key)}`)
    sources.set(key, from)
    if (trimSlash(from) === trimSlash(to)) errors.push(`${from}: redirects to itself`)
    if (isPage(from)) errors.push(`${from}: is an existing page`)
    if (!isPage(to)) errors.push(`${from}: target ${to} is not a page`)
  }
  for (const [from, to] of entries) {
    if (sources.has(trimSlash(to)) && trimSlash(from) !== trimSlash(to)) {
      errors.push(`${from}: target ${to} is itself redirected`)
    }
  }
  return errors
}

const entries = load()
const errors = validate(entries)
if (errors.length) {
  console.error(`Redirect errors (${errors.length}) in .vitepress/config/rewrites.json:`)
  errors.forEach((e) => console.error('  -', e))
  process.exit(1)
}

if (mode === 'check') {
  console.log(`OK: ${entries.length} redirects.`)
  process.exit(0)
}

if (!existsSync(dirname(OUT))) {
  console.error(`${dirname(OUT)} not found: run vitepress build first.`)
  process.exit(1)
}

// both /old and /old/ redirect: links to the old site came with and without the slash
const lines = [
  '# Generated by scripts/redirects.mjs from .vitepress/config/rewrites.json, do not edit.',
  `location = ${OUT_URL} { return 404; }`,
]
for (const [from, to] of entries) {
  const bare = trimSlash(from)
  for (const url of new Set([bare, bare === '/' ? '/' : `${bare}/`])) {
    lines.push(`location = ${url} { return 301 ${to}; }`)
  }
}
writeFileSync(OUT, lines.join('\n') + '\n')
console.log(`Wrote ${entries.length} redirects to ${OUT}.`)
